import type { FinalReport } from './report';

/**
 * The report generated by FinalDiagnosis, handed to the Certificate stage.
 * Module state rather than a store — it is written once and read once.
 */
let last: FinalReport | null = null;

export const setLastReport = (r: FinalReport) => {
  last = r;
};

export const getLastReport = () => last;
